/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#68dba9",
        "secondary-fixed": "#85f8c4",
        "error": "#ba1a1a",
        "tertiary-container": "#fc7c78",
        "primary": "#006c49",
        "on-secondary-fixed": "#002114",
        "on-error-container": "#93000a",
        "on-primary-container": "#00422b",
        "on-primary-fixed": "#002113",
        "on-background": "#161d19",
        "surface-variant": "#dde4dd",
        "on-surface-variant": "#3c4a42",
        "on-surface": "#161d19",
        "tertiary-fixed": "#ffdad7",
        "primary-fixed-dim": "#4edea3",
        "secondary-container": "#82f5c1",
        "tertiary": "#a43a3a",
        "surface": "#f4fbf4",
        "primary-fixed": "#6ffbbe",
        "surface-container-low": "#eef6ee",
        "on-error": "#ffffff",
        "surface-container": "#e8f0e9",
        "primary-container": "#10b981",
        "outline": "#6c7a71",
        "on-tertiary-container": "#711419",
        "on-tertiary": "#ffffff",
        "surface-tint": "#006c49",
        "surface-container-lowest": "#ffffff",
        "secondary": "#006c4a",
        "on-primary-fixed-variant": "#005236",
        "on-secondary-container": "#00714e",
        "inverse-surface": "#2b322d",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#842225",
        "surface-bright": "#f4fbf4",
        "on-secondary-fixed-variant": "#005137",
        "surface-container-high": "#e3eae3",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#dde4dd",
        "inverse-on-surface": "#ebf3eb",
        "background": "#f4fbf4",
        "tertiary-fixed-dim": "#ffb3af",
        "on-tertiary-fixed": "#410005",
        "inverse-primary": "#4edea3",
        "outline-variant": "#bbcabf",
        "surface-dim": "#d4dcd5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        "3xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        sidebar_width: "260px",
        max_content_width: "1280px",
      },
      fontFamily: {
        "h1": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "h1": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h2": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "h3": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
