/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "error": "var(--color-error)",
        "tertiary-container": "var(--color-tertiary-container)",
        "primary": "var(--color-primary)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-error-container": "var(--color-on-error-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-background": "var(--color-on-background)",
        "surface-variant": "var(--color-surface-variant)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-surface": "var(--color-on-surface)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "secondary-container": "var(--color-secondary-container)",
        "tertiary": "var(--color-tertiary)",
        "surface": "var(--color-surface)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-error": "var(--color-on-error)",
        "surface-container": "var(--color-surface-container)",
        "primary-container": "var(--color-primary-container)",
        "outline": "var(--color-outline)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-tertiary": "var(--color-on-tertiary)",
        "surface-tint": "var(--color-surface-tint)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "secondary": "var(--color-secondary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-primary": "var(--color-on-primary)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "surface-bright": "var(--color-surface-bright)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-container-high": "var(--color-surface-container-high)",
        "error-container": "var(--color-error-container)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "background": "var(--color-background)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "inverse-primary": "var(--color-inverse-primary)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-dim": "var(--color-surface-dim)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        "3xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        sidebar_width: "260px",
        max_content_width: "1280px",
      },
      fontFamily: {
        "h1": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "h1": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h2": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "h3": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
